{
    "last_item": null,
        "total_items": "30",
            "first_item": null,
                "page_number": "1",
                    "page_size": "10",
                        "page_items": null,
                            "search_time": "0.074",
                                "page_count": "3",
                                    "events": {
        "event": [
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": null,
                "going_count": null,
                "all_day": "2",
                "latitude": "33.876418",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/concert-bugs-\/E0-001-113812585-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-113812585-7",
                "privacy": "1",
                "city_name": "Smyrna",
                "link_count": null,
                "longitude": "-84.5208672",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2018-11-29 00:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-10-10 01:01:47",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Concert Bugs",
                "venue_address": "1125 Concord Road",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-19 04:31:03",
                "venue_id": "V0-001-012271245-9",
                "tz_city": null,
                "stop_time": "2019-01-31 00:00:00",
                "venue_name": "Smyrna",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/smyrna-\/V0-001-012271245-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30309",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.788922",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/atlanta-symphony-orchestra-et-extraterrestrial-\/E0-001-113216473-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-113216473-9",
                "privacy": "1",
                "city_name": "Atlanta",
                "link_count": null,
                "longitude": "-84.3851208",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-04 20:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-03-25 05:13:51",
                "venue_display": "1",
                "tz_country": null,
                "performers": {
                    "performer": {
                        "creator": "georg005",
                        "linker": "evdb",
                        "name": "Atlanta Symphony Orchestra",
                        "url": "http:\/\/concerts.eventful.com\/Atlanta-Symphony-Orchestra?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000071582-8",
                        "short_bio": "Grammy Award winning orchestra"
                    }
                },
                "title": "Atlanta Symphony Orchestra - ET The Extra-Terrestrial In Concert",
                "venue_address": "1280 Peachtree St",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": {
                    "small": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/037\/007\/841-1.jpeg_\/atlanta-symphony-orchestra-et-extraterrestrial-co-41.jpeg",
                        "height": "48"
                    },
                    "width": "48",
                    "caption": null,
                    "medium": {
                        "width": "128",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/medium\/I0-001\/037\/007\/841-1.jpeg_\/atlanta-symphony-orchestra-et-extraterrestrial-co-41.jpeg",
                        "height": "128"
                    },
                    "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/037\/007\/841-1.jpeg_\/atlanta-symphony-orchestra-et-extraterrestrial-co-41.jpeg",
                    "thumb": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/thumb\/I0-001\/037\/007\/841-1.jpeg_\/atlanta-symphony-orchestra-et-extraterrestrial-co-41.jpeg",
                        "height": "48"
                    },
                    "height": "48"
                },
                "created": "2018-03-25 05:13:51",
                "venue_id": "V0-001-000151895-8",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "Atlanta Symphony Hall",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/atlanta-symphony-hall-\/V0-001-000151895-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30188",
                "going_count": null,
                "all_day": "0",
                "latitude": "34.0990625",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/beatles-tribute-return-\/E0-001-121422264-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-121422264-7",
                "privacy": "1",
                "city_name": "Woodstock",
                "link_count": null,
                "longitude": "-84.5205785",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-06 19:00:00",
                "tz_id": null,
                "description": " <br> About The Return The Return got its start back in 1995 when four young friends got together to play their favorite Beatles songs just for the fun of it. It wasnt long before they played in front of an audience at the request of a friend and as it turned out, were very well received. That showwhich was supposed to be a one time thing--led to another gig, which led to another and so on until the band found themselves playing on a regular basis. They decided to go ahead and make it official. They named themselves the Roaches. As time went on, they began to polish up their act a bit and became fixated on the idea of striving for the highest level of authenticity possible. They wanted to recreate the early sixties Beatles concert experience from the tiniest detail (John Lennons on-stage gum-chewing) to the biggest, most expensive details (using exact replicas of the instruments and gear the Beatles used). While they were learning to comb their moptops just right and finding the right Beatle boots and black suits to wear, they were also learning each song note for note, rhythm for rhythmgetting the signature moves and looks of the Fab Four down pat, too. They practiced relentlessly--with a growing passion for getting their show just right. In the years that followed a few members came and went, and the band took on a more professional presence. They got an agent, changed their name to the Return, and began to command the attention of more widely renowned clients not only in the United States, but in multiple other countries as wellincluding England. They are known as one of the best Beatles cover bands in the country for a reason, and it was evident from our fans reaction to hearing them play. Scott Cunningham ~ Director of Entertainment ~ Atlanta Braves Today the band still strives to maintain the utmost level of authenticity in their show. In fact, they are known for it. Theyve played thousands of showstheatres, festivals, fairs, casinos, cruise ships, colleges and universities, weddings, birthday parties, bar mitzvahs--as well as countless corporate events for companies like Coca Cola, ABC, Hard Rock Cafe, and Volkswagen International--and the reaction is the same every time. People are amazed at how much the Return sounds and looks just like the Beatles. They were great! Their energy and enthusiasm jumps off the stage. It was quite fun to watch them and imagine what it must have been like at an actual Beatles concert! Tony Perkins ~ Good Morning America The Return has crafted a truly authentic, entertaining, and very exciting show. And in doing so, the band not only delivers a near perfect reproduction of a live Beatles concert--they capture the very essence of the Beatles themselves. Seeing the Return is like traveling back to Liverpool in the early 1960s...The Beatles live thanks to the Return! Jim Weiss~Senior VP of PR ~ Turner Broadcasting Highlights - Performed a private concert at Abbey Road Studios in London, England- In Japan - headlined the 40th anniversary celebration of the Beatles visit to Tokyo- Performed at the 2012 US Olympic Swim Trials in Omaha, NE- The official band of the Hard Rock Cafes 30th anniversary celebration- Debuted their Sgt Peppers & Beyond show in front of 10,000 fans in Hermosillo, Mexico- Performed a live concert on XM Radio for the 40th anniversary of the Beatles 1st US visit- Recorded the Happy Birthday jingle for BeatlesRadio.com- The Atlanta Braves 2009 Band Of The Year- Performed at the Cavern in Liverpool, England- Provided the vocals for the ivideosongs.com instructional series- Official band of the 2008 Beatle Brunch Cruise- Performed at Beatles Fest West in San Francisco, CA- Headlined the PATH Rocks 2009 Paul McCartney pre-party concert- The official band of the 2003 Magical History Tour in London & Liverpool- Performed at the 2011 Golden Goggle Awards hosted by Kevin Nealon- Appeared nationally on CNN, TBS, and VH1- Mentioned in Time, Forbes, Bridal, and Mix Magazines- Entertained guests at private parties for the CEO of Coca Cola, the President of ABC Radio, media mogul Ted Turner, and Hollywood producer Jerry Bruckheimer- Shared the stage with legendary and well known acts such as:Little Richard, Jerry Lee Lewis, The Monkees, Peter Noone, Blood, Sweat & Tears, Chubby Checker,The Association, BJ Thomas, Flo & Eddie (The Turtles), Tommy James & The Shondells, Johnny Rivers,The Grass Roots, Chuck Negron (Three Dog Night), Jerry Lewis & The Playboys, Billy J Kramer, 38 Special",
                "modified": "2018-12-30 17:41:55",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Beatles Tribute - The Return",
                "venue_address": "8722 Main Street",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-12-20 22:52:57",
                "venue_id": "V0-001-009824650-1",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "MadLife Stage & Studios",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/madlife-stage-studios-\/V0-001-009824650-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30030",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.7739746",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/cody-marlowe-\/E0-001-117794000-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-117794000-6",
                "privacy": "1",
                "city_name": "Decatur",
                "link_count": null,
                "longitude": "-84.2962715",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-05 21:15:00",
                "tz_id": null,
                "description": " with Austin Coleman<br> American born singer-songwriter and roots-rock artist Cody Marlowe found his inspiration at an early age in the soulful sounds of B.B. King, Merle Haggard, and the Allman Brothers. In the small town of Clermont, Georgia, Cody was born into a family of music. He learned how to play piano from his great-aunt and his mother, took guitar lessons with his grandpa and uncle, and was influenced vocally by his grandma, aunt, and sister. Katie (sister) sings with Cody in concerts and on many recordings. Marlowes songs explore the polarities of good and evil in an intriguing blend of lyrics featuring lost loves and hopeful musings.His 2013 album, Silver and Gold, is his third release since his first EP, Where You Are, released in 2010 and his first full length, Eighty Nine, released in 2011. For &quot;Silver and Gold,&quot; Marlowe teamed up with brothers, producer\/drummer Kevin Sellors and bass player Ryan Sellors, to form the back-up band the Dead Flowers. During the recording process, Marlowe recruited Joey Huffman on organ (Hank Jr., Matchbox 20) and Nathan Bedingfield on electric guitar (Aaron Shust). Silver and Gold is a return to the roots of rock n roll, country, blues, and honest songwriting; reminiscent of Tom Petty and the Black Crowes but with a modern edge inspired by childhood in the 90s.Released in 2016, the EP entitled &quot;Songs For Your Television&quot; contains six songs; four original tunes and two public domain classics featuring their personal interpretation. Head Held High is featured on the TLC aired program &quot;Welcome to Myrtle Manor.&quot; Rockin&#39; Robin and Nobody Knows You were both used in independent short-films by Oakey Productions.Cody&#39;s side project, &quot;Foxhollow,&quot; is a folk rock band hailing from Atlanta, Georgia. Founded by the songwriting duo, Cody Marlowe and Joel Hoffman, Foxhollow have toured regionally over the past 2 years with shows at Eddies Attic, Vinyl, and a show with Eddie Money at 37 Main. Foxhollow has one self-titled album featuring fan favorites such as &quot;Hello&quot; and &quot;Crazy.&quot;",
                "modified": "2018-12-18 21:52:15",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Cody Marlowe",
                "venue_address": "515-B N. McDonough Street",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-09-06 19:35:46",
                "venue_id": "V0-001-000445186-7",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "Eddie's Attic",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/eddies-attic-\/V0-001-000445186-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30308",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.7716248",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/stranger-tribute-band-\/E0-001-119564549-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-119564549-7",
                "privacy": "1",
                "city_name": "Atlanta",
                "link_count": null,
                "longitude": "-84.3674226",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-04 20:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-10-30 18:01:28",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "The Stranger - Tribute Band",
                "venue_address": "650 North Avenue",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-10-30 18:01:28",
                "venue_id": "V0-001-010766474-2",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "City Winery - Atlanta",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/city-winery-atlanta-\/V0-001-010766474-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30316",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.7404569",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/feel-good-fridays-w-hypno-\/E0-001-117339090-2@2019011115?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-117339090-2@2019011115",
                "privacy": "1",
                "city_name": "Atlanta",
                "link_count": null,
                "longitude": "-84.3459906",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-11 15:00:00",
                "tz_id": null,
                "description": " TEN ATL is the only place to be on a Friday night. Come enjoy sounds by Guest DJ and the Hypnotic Band. Let them take you on a musical rollercoaster, playing sounds from the 80s to present day HIP HOP featuring the baddest female drummer in the land, Monica a.k.a MzDrummer. Fridays are all about feeling good and catching a vibe. $10 Hookahs Before 10pm EVERYDAY!\u00a0 DJ KASHII 1ST & 3RD FRIDAYS Guest DJ 2ND & 4TH FRIDAYS\u00a0 Hypnotic Band at 10pm INDULGE \u00a0- TASTE - PLAY @TENATL\u00a0 ",
                "modified": "2018-10-04 04:36:48",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "FEEL GOOD FRIDAYS w\/ HYPNOTIC BAND featuring MZ. Drummer",
                "venue_address": "495 Flat Shoals Avenue Southeast",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": "on various days",
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": {
                    "small": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/040\/972\/674-6.jpeg_\/feel-good-fridays-w-hypnotic-band-feat-74.jpeg",
                        "height": "48"
                    },
                    "width": "48",
                    "caption": null,
                    "medium": {
                        "width": "128",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/medium\/I0-001\/040\/972\/674-6.jpeg_\/feel-good-fridays-w-hypnotic-band-feat-74.jpeg",
                        "height": "128"
                    },
                    "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/040\/972\/674-6.jpeg_\/feel-good-fridays-w-hypnotic-band-feat-74.jpeg",
                    "thumb": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/thumb\/I0-001\/040\/972\/674-6.jpeg_\/feel-good-fridays-w-hypnotic-band-feat-74.jpeg",
                        "height": "48"
                    },
                    "height": "48"
                },
                "created": "2018-08-22 14:40:10",
                "venue_id": "V0-001-011936731-0",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "TEN ATL",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/ten-atl-\/V0-001-011936731-0?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": null,
                "going_count": null,
                "all_day": "0",
                "latitude": "34.0753",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/soulful-zekepotterkhemist-\/E0-001-119797790-1@2019010520?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-119797790-1@2019010520",
                "privacy": "1",
                "city_name": "Alpharetta",
                "link_count": null,
                "longitude": "-84.2942",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-05 20:30:00",
                "tz_id": null,
                "description": " EACH & EVERY WEEK AT FIREFLY WE BRING SOME OF THE HOTTEST LIVE ENTERTAINMENT IN THE ENTIRE CITY!!! SEPTEMBER WE&#39;VE HAD SOME OF THE BEST & TALENTED ARTIST PERFORMING EACH & EVERY SATURDAY!!! * * * * * * *\u00a0 And this Saturday, November 10th the Soulful &quot;Zeke Potter & The Khemistry Live Band&quot; will be Live at Firefly!\u00a0 2 Shows : 8:30pm-9:30pm & 10pm-11pm OPEN TIL 1AM | DRINK SPECIALS | DINNER | APPETIZERS | LIVE MUSIC BIRTHDAY CELEBRATIONS, DATE NIGHT, GIRLS NIGHT OUT OR JUST COME OUT AND ENJOY THE AMAZING LIVE MUSIC, AWESOME FOOD AND DRINKS RSVP NOW!!! All Live @Firefly_Atl GIRL&#39;S NIGHT, DATE NIGHT, A SPECIAL CELEBRATION OR JUST WANT TO GET OUT AND HAVE A GOOD TIME; FIREFLY IS THE PLACE TO BE!!! AND AS ALWAYS...\u00a0 Doors Open at 7pm 1st Showtime Starts @ 8:30pm and 2nd Showtime 10pm Come enjoy Appetizers, Dinner, Cocktails & more!!! Smooth Contemporary Jazz * Pop * Soul * Smooth R&B Cocktail Specials | Free Parking | Free Entrance| Amazing Food & More RSVP NOW FOR ALL SHOWS NOW!!! 3070 Windward Plaza, Alpharetta, GA 30005\u00a0 For Other Info, Table Reservations, Free Birthday Parties with a Bottle of Free Champagne & More:: E-mail: JanetAtFirefly@gmail.com or Call 770.609.8235 Or Vistit:\u00a0www.FireFlyAlpharetta.com IF PURCHASING A GUARANTEED SEAT, THERE IS NO REFUNDS ",
                "modified": "2018-11-07 05:26:01",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "THE SOULFUL \"ZEKE POTTER & KHEMISTRY LIVE BAND\" WILL BE LIVE AT FIREFLY THIS SATURDAY",
                "venue_address": "3070 Windward Plaza",
                "geocode_type": "City Based GeoCodes",
                "tz_olson_path": null,
                "recur_string": "on various days",
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": {
                    "small": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/041\/682\/240-0.jpeg_\/soulful-zekepotterkhemistryliveband-wi-40.jpeg",
                        "height": "48"
                    },
                    "width": "48",
                    "caption": null,
                    "medium": {
                        "width": "128",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/medium\/I0-001\/041\/682\/240-0.jpeg_\/soulful-zekepotterkhemistryliveband-wi-40.jpeg",
                        "height": "128"
                    },
                    "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/small\/I0-001\/041\/682\/240-0.jpeg_\/soulful-zekepotterkhemistryliveband-wi-40.jpeg",
                    "thumb": {
                        "width": "48",
                        "url": "\/\/d1marr3m5x4iac.cloudfront.net\/images\/thumb\/I0-001\/041\/682\/240-0.jpeg_\/soulful-zekepotterkhemistryliveband-wi-40.jpeg",
                        "height": "48"
                    },
                    "height": "48"
                },
                "created": "2018-11-06 07:44:07",
                "venue_id": "V0-001-013057864-7",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "Firefly Restaurant & Bar",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/firefly-restaurant-bar-\/V0-001-013057864-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30097",
                "going_count": null,
                "all_day": "0",
                "latitude": "34.0025716",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/street-fighting-band-rolling-stones-tribute-\/E0-001-118656828-4?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-118656828-4",
                "privacy": "1",
                "city_name": "Duluth",
                "link_count": null,
                "longitude": "-84.1449913",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-05 20:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-09-30 12:18:06",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Street Fighting Band - Rolling Stones Tribute",
                "venue_address": "3116 Main Street",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-09-30 12:18:06",
                "venue_id": "V0-001-011076729-8",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "Red Clay Music Foundry",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/red-clay-music-foundry-\/V0-001-011076729-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30033",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.825946",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/honeywood-webster-\/E0-001-120426891-4?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-120426891-4",
                "privacy": "1",
                "city_name": "Decatur",
                "link_count": null,
                "longitude": "-84.2905",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-05 20:00:00",
                "tz_id": null,
                "description": " <p>HONEYWOOD:<p><strong>Honeywood\u00a0<\/strong>is a five-piece bluegrass jam band from Atlanta playing a mix of originals with rock and folk classics in bluegrass style. Formed in 2014, the band has an intense and unique sound featuring acoustic guitar, mandolin\/banjo, fiddle, bass and drums. A Honeywood show is full of great singing, hot pickin&#39;, dancing and fun for all ages...\u00a0a BLUEGRASS PARTY BAND!<br> \u00a0<p>WEBSTER:<p>Webster&#39;s music enjoys wide appeal. The 5-piece band formed in 2005 and covers artists including The Grateful Dead, Bob Dylan, Neil Young, Rolling Stones, Tom Petty, Phish, REM, Van Morrison, among others. Their focus is on improvisational and inspirational live music. The band\u2019s tangible energy takes an audience on a musical journey, encouraging a fun and active experience. They have performed at numerous venues throughout greater Atlanta, sharing the stage with major headline acts including Government Mule, Chris Robinson, Drive-By Truckers & The Wailers. Come check out Webster!<p>\u00a0<\/p><\/p><\/p><\/p><\/p>",
                "modified": "2018-11-24 02:25:30",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Honeywood & Webster",
                "venue_address": "2836 Lavista Road",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-11-24 02:25:30",
                "venue_id": "V0-001-010701663-5",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "The Vista Room",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/the-vista-room-\/V0-001-010701663-5?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America\/New_York",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "GA",
                "postal_code": "30307",
                "going_count": null,
                "all_day": "0",
                "latitude": "33.7636046",
                "groups": null,
                "url": "http:\/\/atlanta.eventful.com\/events\/tribute-celebration-allman-brothers-band-\/E0-001-120422306-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-120422306-3",
                "privacy": "1",
                "city_name": "Atlanta",
                "link_count": null,
                "longitude": "-84.3509632",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Georgia",
                "start_time": "2019-01-05 19:30:00",
                "tz_id": null,
                "description": " with Harvest Moon- The Music of Neil Young<br> TRIBUTE - a celebration of The Allman Brothers Band is a powerful 8 piece group that faithfully recreates the music of one of the finest bands of all time. Since its founding in 2013, Atlanta-based TRIBUTE has earned a reputation as the source for the authentic ABB sound around Atlanta and throughout the Southeast. Rigged with vintage equipment, they interpret the Allman catalog in such a way that these songs written in the 60s and 70s come alive again. If the band has learned anything from performing these songs, it is the realization that even though The Allman Brothers Band has shut down, their music maintains the same power over people just as it did 45 years ago. It is a phenomenon TRIBUTE gladly verifies every time they hit the stage. TRIBUTE recalls that unique period in American rock, when psyche-delia ebbed and The ABB informed us what jazz, rock, country and blues could sound like. Comprised of musicians with decades of performance experience, the members of TRIBUTE bring their shared love of The Allman Brothers Band to life when it comes time for hittin&#39; the note. www.TributeABB.comwww.facebook.com\/TributeABBwww.twitter.com\/TributeABB",
                "modified": "2018-11-23 14:17:07",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Tribute- a celebration of The Allman Brothers Band",
                "venue_address": "1099 Euclid Avenue",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-11-23 14:17:07",
                "venue_id": "V0-001-001449195-2",
                "tz_city": null,
                "stop_time": null,
                "venue_name": "Variety Playhouse",
                "venue_url": "http:\/\/atlanta.eventful.com\/venues\/variety-playhouse-\/V0-001-001449195-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            }
        ]
    }
}